### ISSUE TITLE
ARQUIVOS NO REPOSITORIO

### ISSUE THREAD

**Issue by rosenclever** [joaovictor199600/c-_part2#1]
Deixe no repositório seus arquivos descompactados a partir da pasta do projeto, senão quando for clonado terá que ser extraído.

**Comment by joaovictor199600** [comment]
ta bom professor é que n estou muito acostumado


Em qua., 29 de set. de 2021 às 18:43, Rosenclever Lopes Gazoni <
***@***.***> escreveu:
